<<<<<<< HEAD
import type { Metadata } from 'next'
import './globals.css'

// The favicon comes from app/icon.png automatically (Next.js file convention)
export const metadata: Metadata = {
  title: 'FormCheck',
  description: 'Exercise form feedback using your camera',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
>>>>>>> 11bfd34f8c1c95c1e8d70772ffdb4036db112f8b
}
